Changed how packages are handled as script arguments

diff --git a/trunk/src/pkgadd.in b/trunk/src/pkgadd.in
--- a/trunk/src/pkgadd.in
+++ b/trunk/src/pkgadd.in
@@ -30,11 +30,6 @@ ${0##*/} [<options>] <package_list>
 
 Install packages in the order given on the commandline.
 
-Package list:
--f, --profile <profile> ...	Specify files containing package profiles
--p, --package <package> ...	Specify packages by name (default)
---				Treat remaining arguments as packages/profiles
-
 Options (must precede package list):
 -b, --backup-installed		Backup and remove any existing installations
 -c, --config <config_file>	Specify alternative configuration file
@@ -45,6 +40,7 @@ Options (must precede package list):
 -r, --remove-installed		Remove any existing installations
 -R, --remove-failed		Cleanup files from any failed installations
 -s, --stage <stage_number>	Specify stage 0, 1 or 2 (default = 2)
+--				Treat remaining arguments as packages
 
 -h, -?, --help			Show this help screen
 -v, --version			Show version information
@@ -67,8 +63,6 @@ while [[ "$1" == -* ]]; do
 		(-d|--download)			download=yes ;;
 
 		(--config=*)			config="${1#--config=}" ;;
-
-		(-f|--profile|-p|--package)	break ;;
 
 		(-h|-\?|--help)			usage ;;
 
@@ -97,56 +91,56 @@ while [[ "$1" == -* ]]; do
 	shift
 done
 
+# The remaining arguments should all be packages.
+(( $# == 0 )) && script_usage_err "no packages to install"
+
 source_config
-find_profiles "$@"
 
 # Download packages if told to.
 if [[ "$download" == yes ]]; then
 	echo "Downloading needed files..."
-	pkgget --config="$config" --profile "${profile_listp[@]}" ||
-	error "downloading failed"
+	pkgget --config="$config" "$@" || error "downloading failed"
 fi
 
 # If there is more than one package, install each in its own instance.
-if (( ${#profile_list[@]} > 1 )); then
-	for profile in "${profile_list[@]}"; do
+if (( $# > 1 )); then
+	for package in "$@"; do
 		"$0" --config="$config" ${installed:+--$installed-installed} \
-		     ${failed:+--$failed-failed} --stage=$stage \
-		     --profile "$profile" ||
-		error "failed in $profile"
+		     ${failed:+--$failed-failed} --stage=$stage "$package" ||
+		error "installation of $package failed"
 	done
 	finish
 fi
 
 # There is only one package to install.  Do so in this instance.
-open_package "${profile_list[0]}"
+open_package "$1"
 
 log_echo
 log_echo "	----- $name_ver -----"
 
 log_echo
 log_echo "Unarchiving & patching $name..."
-pkgunpack --config="$config" --stage=$stage --profile "$profile" ||
+pkgunpack --config="$config" --stage=$stage "$package" ||
 error "unarchiving or patching $name failed"
 
 if is_func build_pkg; then
 	log_echo
 	log_echo "Building $name..."
-	pkgbuild --config="$config" --stage=$stage --profile "$profile" ||
+	pkgbuild --config="$config" --stage=$stage "$package" ||
 	error "building $name failed"
 fi
 
 if [[ "$check" == yes ]]; then
 	log_echo
 	log_echo "Running $name checksuite..."
-	pkgcheck --config="$config" --stage=$stage --profile "$profile" ||
+	pkgcheck --config="$config" --stage=$stage "$package" ||
 	error "checksuite failed for $name"
 fi
 
 log_echo
 log_echo "Installing $name..."
 pkginstall --config="$config" ${installed:+--$installed-installed} \
-	   ${failed:+--$failed-failed} --stage=$stage --profile "$profile" ||
-error "installing $name failed"
+	   ${failed:+--$failed-failed} --stage=$stage "$package" ||
+error "installation of $name failed"
 
 finish
